# This is a basic workflow to help you get started with Actions

name: CI Surge

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Install Node js
    - name: Setup Node Js
      uses: actions/setup-node@v2-beta
      with:
         node-version: 12
    
     # Install Npm
    - name: Instaling Yarn
      uses: Borales/actions-yarn@v2.3.0
     
     # Building For Production
    - name: Building For Production With Yarn
      with: 
        cmd: install
          
    # Install Surge
    - name: Installing Surge
      run: npm install surge --global
    
    # Deploying
    - name: Deploying App to Surge
      run: surge ./build expensetracker_arslanali.surge.sh ${{ secrets.SURGE_TOKEN }}  

